import type { AgentState } from './types';
import { MODEL, createInitialMessages } from '@/config';

export const createInitialState = (): AgentState => ({
  messages: createInitialMessages(),
  inputChars: [],
  pasteRanges: [],
  historyEntries: [],
  queuedSubmissions: [],
  cursor: 0,
  scrollOffset: 0,
  busy: false,
  busyStatusText: null,
  closed: false,
  liveAssistantText: '',
  liveReasoningText: '',
  selectedSuggestion: 0,
  currentModel: MODEL,
  thinkingMode: 'auto',
  lastPromptTokens: 0,
  lastOutputTokens: 0,
  lastReasoningTokens: 0,
  totalCost: 0,
  abortController: null,
  abortConfirmationPending: false,
  abortRequested: false,
  steerRequested: false,
  exitConfirmationPending: false,
  pendingApproval: null,
  footerNotice: null,
  autoRunEnabled: false,
  autoCompactEnabled: true,
  commandApprovalSessionAllowed: false,
  editApprovalSessionAllowed: false,
  compacting: false
});
