import { execSync } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import path from 'node:path';
import pkg from '../package.json' with { type: 'json' };

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outputPath = path.join(__dirname, '../src/config/version.ts');

const buildUnixTime = process.env.APP_BUILD_UNIX_TIME ?? `${Math.floor(Date.now() / 1000)}`;

const gitHash = process.env.APP_GIT_HASH ?? getGitHash();
const buildVersion = `${pkg.version}.${buildUnixTime}-g${gitHash}`;

const content = `// generated by scripts/generate-version.mjs\nexport const BUILD_VERSION = '${buildVersion}';\n`;
await writeFile(outputPath, content);

function getGitHash() {
  try {
    return execSync('git rev-parse --short=8 HEAD', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim();
  } catch {
    return 'unknown';
  }
}
